jenkins:
  systemMessage: |
    Welcome to jenkins configuration-as-code demo by Springjunky. 
    For more information look in the official repo https://github.com/Praqma/praqma-jenkins-casc
  agentProtocols:
    - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: secret
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "View/Read:anonymous"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    SYSTEM
              id:       gitlab-username-password
              username: ${github_user:-scott}
              password: ${github_pass:-tiger}
          - gitLabApiTokenImpl:
              scope: SYSTEM
              id: gitlab-api-token
              apiToken: "fake_dummy_qwertyuiopasdfghjklzxcvbnm"
              description: "Gitlab Token"
          # Warning, File-Credentials with given secretBytes should broken between Jenkins-Upgrades !!
          - file:
              scope: GLOBAL
              id: secret-file-no-42
              description: "File with Ansible-Password"
              fileName: "vault_pass.txt" 
              secretBytes: "{Z72A5MxJUQAH31MHDphPPIoz6JDZQwr0B1O4PswnmKs=}"
          - string:
              description: "This is a secret text"
              id: "secret-text-id"
              scope: GLOBAL
              secret: "se3cr3t"
              
jobs:
  - script: > 
      job ('ShowSecret') {
       description('Job created with Jenkins-job-dsl and config-as-code-pluign') 
        wrappers {
          credentialsBinding {
            string {
              variable('MY_SECRET')
              credentialsId('secret-text-id')
            }
          }
        }
        steps {
          shell { command ("set -x \n SECRET=\$(echo \$MY_SECRET |  awk '{print toupper(\$0)}')\n"+
                           "echo \"My Uppercase Secret Text \$SECRET \" ")
          }
        }
      }    
unclassified:
  gitlabconnectionconfig:
    connections:
    - apiTokenId: gitlab_token
      clientBuilderId: "autodetect"
      connectionTimeout: 20
      ignoreCertificateErrors: true
      name: "my_gitlab_server"
      readTimeout: 10
      url: "https://gitlab.com/"
  jiraProjectProperty:
    sites:
      url: https://my.jira.de  
  
  